# https://app.circleci.com/pipelines/github/o-mdr/pa-pattern-complexity
version: 2.1

jobs:
  build-test-job:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      # TODO add support for building
      # - run:
      #     working_directory: ~/project/App.Tests
      #     name: Run tests
      #     command: |
      #       dotnet test
workflows:
  build-test-workflow:
    jobs:
      - build-test-job
