# https://app.circleci.com/pipelines/github/o-mdr/pa-pattern-complexity
version: 2.1

jobs:
  build-test-job:
    docker:
      - image: microsoft/dotnet:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /app
    steps:
      - checkout
      # TODO add support for building
      # - run:
      #     working_directory: ~/project/App.Tests
      #     name: Run tests
      #     command: |
      #       dotnet tests
workflows:
  build-test-workflow:
    jobs:
      - build-test-job:
          context: omdr
