version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  # Building with GCC
  build_job_gcc:
    docker:
      - image: gcc:10.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /pa-pattern-complexity
    steps:
      - checkout
      - run:
          name: Run bootstrap
          command: ./script/bootstrap
      - run:
          name: Run CI script
          command: ./script/cibuild
      - store_test_results:
          path: builddir/meson-logs
      - store_artifacts:
          path: builddir/compressed-artifacts/pa-pattern-complexity.tar.gz
          destination: pa-pattern-complexity.tar.gz
      - store_artifacts:
          path: builddir/compressed-artifacts/pa-pattern-complexity.src.tar.gz
          destination: pa-pattern-complexity.src.tar.gz

  # Building with clang
  build_job_clang:
    docker:
      - image: silkeh/clang:10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /pa-pattern-complexity
    steps:
      - checkout
      - run:
          name: Run bootstrap
          command: ./script/bootstrap
      - run:
          name: Run CI script
          command: ./script/cibuild
      - store_test_results:
          path: builddir/meson-logs
      - store_artifacts:
          path: builddir/compressed-artifacts/pa-pattern-complexity.tar.gz
          destination: pa-pattern-complexity.tar.gz

  # Building with MSVC
  build_job_msvc:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Download Cygwin installer
          shell: bash.exe
          command: curl -sSJOL https://cygwin.com/setup-x86_64.exe
      - run:
          name: Install Cygwin and required packages
          command: .\setup-x86_64.exe -q -s https://mirrors.kernel.org/sourceware/cygwin/ -P python3,meson,gcc-g++
      - run:
          name: Bootstrap with Cygwin
          shell: C:\\cygwin64\\bin\\bash.exe --login -eo pipefail
          command: |
            CIRCLE_WORKING_DIRECTORY=$(eval "echo $CIRCLE_WORKING_DIRECTORY")
            pwd
            ls -alh
            ls -alh /
            ls -alh /cygdrive
            cd $CIRCLE_WORKING_DIRECTORY
            ./script/bootstrap
      - run:
          name: Run CI script
          command: ./script/cibuild
      - store_artifacts:
          path: builddir/compressed-artifacts/pa-pattern-complexity.tar.gz
          destination: pa-pattern-complexity.tar.gz

workflows:
  build_workflow:
    jobs:
      - build_job_msvc:
          context: omdr
      - build_job_clang:
          context: omdr
      - build_job_gcc:
          context: omdr
