#!/bin/bash

# Install dependencies that the application requires for building and running.
# Tested on Ubuntu machine

if [ $(id -u) != 0 ]; then
    echo "This script requires sudo:"
    echo "sudo $0 $*"
    exit 1
fi

cd "$(dirname "$0")/.."

echo "==> Installing r-project key for software installation"
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'

echo "==> Updating..."
apt-get -qq update;

echo "==> Installing required packages"
apt-get install -yqq \
  unzip \
  curl \
  gnupg2 \
  git \
  shellcheck \
  r-base \
  python3 python3-pip python3-setuptools python3-wheel ninja-build build-essential

echo "==> Installing clang tools..."
apt-get -y install clang clang-format

echo "==> Installing meson..."
pip3 install --upgrade meson

echo "==> Reloading profile file"
. ~/.profile
export PATH=$PATH:$HOME/.local/bin

echo "==> Setting up meson environment"
meson setup builddir

echo "Bootstraping is done"
